import blockContent from './blockContent'
import category from './category'
import post from './post'
import author from './author'
import homePage from './homePage'
import issue from './issue'
import aboutPage from './aboutPage'
import teamMember from './teamMember'
import contactPage from './contactPage'
import numeroPage from './numeroPage'
import video from './video'
import videosPage from './videosPage'
import festivalPage from './festivalPage'
import festivalPartner from './festivalPartner'
export const schemaTypes = [post, author, category, blockContent, homePage, issue, aboutPage, teamMember, contactPage, numeroPage, video, videosPage, festivalPage, festivalPartner]
